swagger: '2.0'
info: 
  title: Edu-connect, ACN, Arewa Hub server API Documentation
  description: API documentation for Edu-connect, ACN, Arewa Hub.
  version: 1.0
  contact: 
    email: successakinyemi365@gmail.com
  license:
    name: Apache 2.0
    url: 'http://apache.org/'
host: edu-connect-admin-server.onrender.com
basePath: /               
schemes:
  - https

paths:
  /:
    get:
      summary: Home GET request
      description: Server base endpoint
      responses:
        200:
          description: Success

  /api/educonnect/contactUs/sendMessage:
    post:
      summary: send a contact us message
      description: send a contact us message
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - phoneNumber
              - message
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              phoneNumber:
                type: string
              message:
                type: string
      responses:
        201: 
          description: Message Submitted Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/educonnect/faq/getAllFaq:
    get:
      summary: Get Faq for educonnect
      description: get frequently asked questions for educonnect website
      responses:
        200:
          description: Success
        500:
          description: Server error 

  /api/educonnect/team/getAllTeam:
    get:
      summary: Get team memebesr for arewa hub
      description: Get team memebesr for arewa hub
      responses:
        200:
          description: Success
        500:
          description: Server error   

  /api/educonnect/team/getTeam/{id}:
    get:
      summary: Get a specific team member
      description: Get a specific team member using there `teamMemberId`.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the team member to retrieve
          schema:
            type: string
      responses:
        201: 
          description: Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/acn/contactUs/sendMessage:
    post:
      summary: send a contact us message
      description: send a contact us message
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - phoneNumber
              - message
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              phoneNumber:
                type: string
              message:
                type: string
      responses:
        201: 
          description: Message Submitted Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/acn/faq/getAllFaq:
    get:
      summary: Get Faq for educonnect
      description: get frequently asked questions for educonnect website
      responses:
        200:
          description: Success
        500:
          description: Server error 

  /api/acn/newsAndUpdates/getUserAllNewsAndUpdates:
    get:
      summary: Get all News and updates (blog post)
      description: Get all News and updates (blog post)
      responses:
        200:
          description: Success
        500:
          description: Server error 

  /api/acn/newsAndUpdates/getUserANewsAndUpdates/{id}:
    get:
      summary: Get a News and updates (blog post)
      description: Get a News and updates (blog post)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the blog post to retrieve
          schema:
            type: string
      responses:
        201: 
          description: Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/arewahub/product/fetchProducts:
    get:
      summary: Get product for arewa hub
      description: Get product for arewa hub
      responses:
        200:
          description: Success
        500:
          description: Server error   

  /api/arewahub/product/product/{id}:
    get:
      summary: Get a specific product item
      description: Get a specific product item using its `productId`.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the product to retrieve
          schema:
            type: string
      responses:
        201: 
          description: Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/arewahub/orders/newOrder:
    post:
      summary: New order by customers
      description: Handle new order takes items as an array of object of id (of product) and quantity (of product)
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - customerName
              - customerEmail
              - phoneNumber
              - address
              - items
            properties:
              customerName:
                type: string
              customerEmail:
                type: string
              phoneNumber:
                type: string
              address:
                type: string
              items:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: "The ID of the product"
                    quantity:
                      type: integer
                      description: "The quantity of the product (default is 1)"
      responses:
        201: 
          description: Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/arewahub/events/getEvents:
    get:
      summary: Get events for arewa hub
      description: Get events for arewa hub
      responses:
        200:
          description: Success
        500:
          description: Server error   

  /api/arewahub/events/getPastEvents:
    get:
      summary: Get past events for arewa hub
      description: Get past events for arewa hub
      responses:
        200:
          description: Success
        500:
          description: Server error   

  /api/arewahub/events/getFutureEvents:
    get:
      summary: Get future events for arewa hub
      description: Get future events for arewa hub
      responses:
        200:
          description: Success
        500:
          description: Server error   

  /api/arewahub/events/getEvent/{id}:
    get:
      summary: Get a specific events data
      description: Get a specific events data using its `eventId`.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the events to retrieve
          schema:
            type: string
      responses:
        201: 
          description: Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/arewahub/faq/getAllFaq:
    get:
      summary: Get Faq for educonnect
      description: get frequently asked questions for educonnect website
      responses:
        200:
          description: Success
        500:
          description: Server error 

  /api/arewahub/team/getAllTeam:
    get:
      summary: Get team memebesr for arewa hub
      description: Get team memebesr for arewa hub
      responses:
        200:
          description: Success
        500:
          description: Server error   

  /api/arewahub/team/getTeam/{id}:
    get:
      summary: Get a specific team member
      description: Get a specific team member using there `teamMemberId`.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the team member to retrieve
          schema:
            type: string
      responses:
        201: 
          description: Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/acn/contactUs/sendMessage:
    post:
      summary: send a contact us message
      description: send a contact us message
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - phoneNumber
              - message
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              phoneNumber:
                type: string
              message:
                type: string
      responses:
        201: 
          description: Message Submitted Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/acn/donation/newDonation:
    post:
      summary: make a new donation
      description: Make a new Donation
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - phoneNumber
              - country
              - donationType
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              phoneNumber:
                type: string
              country:
                type: string
              donationType: 
                type: string
      responses:
        201: 
          description: Donation Submitted Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/acn/team/getAllTeam:
    get:
      summary: Get team memebesr for african childe network
      description: Get team memebesr for african childe network
      responses:
        200:
          description: Success
        500:
          description: Server error   

  /api/acn/team/getTeam/{id}:
    get:
      summary: Get a specific team member
      description: Get a specific team member using there `teamMemberId`.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the team member to retrieve
          schema:
            type: string
      responses:
        201: 
          description: Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/eduafrica/contactUs/sendMessage:
    post:
      summary: send a contact us message
      description: send a contact us message
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - phoneNumber
              - message
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              phoneNumber:
                type: string
              message:
                type: string
      responses:
        201: 
          description: Message Submitted Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/testimony/getSectionActiveTestimonies/:value:
    get:
      summary: Get Testimonies form testifiers
      description: Get Testimonies form testifiers value parameters = 'educonnect', 'acn', 'arewahub'
      responses:
        200:
          description: Success
        400:
          description: User error
        500:
          description: Server error 

  /api/suscribe/addSuscriber:
    post:
      summary: Add user to news letter
      description: This endpoint add user to newdletter list. requires user email, and website to identify the website user want to subscribe to website value options = ['educonnect', 'acn', 'arewahub']
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - email
              - website
            properties:
              email:
                type: string
              website:
                type: string
      responses:
        201: 
          description: Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/testimony/newTestimony:
    post:
      summary: Drop feedbacks by users
      description: Drop feedbacks by users
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - firstName
              - lastName
              - testimony
              - position
              - website
            properties:
              firstName:
                type: string
              lastName:
                type: string
              position:
                type: string
              website:
                type: string
              testimony:
                type: string
      responses:
        201: 
          description: Testimony Submitted Successful
        400:
          description: User error
        500: 
          description: Server error
